version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
    #volumes:
     # - ./src:/app/src  # Only for DEV ENVIROMENT
    command: >
      sh -c "pipenv run flask db upgrade &&
             pipenv run gunicorn wsgi:application --chdir src --bind 0.0.0.0:3001"

volumes:
  postgres-data:
